// Native gameplay tags shared by every system.
// Health and injury tags drive movement and animation (Phase 2);
// input tags link Enhanced Input actions to code (see Input/VeilfallInputConfig.h).

#pragma once

#include "NativeGameplayTags.h"

namespace VeilfallTags
{
	// Input
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Aim);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Fire);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Reload);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dodge);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Knife);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_QuickTurn);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ShoulderSwap);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Flashlight);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Inventory);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Map);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Pause);

	// Health states (exactly one is active on the player)
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Health_State_Fine);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Health_State_Caution);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Health_State_Danger);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Health_State_Dead);

	// Injury conditions (any number can stack)
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Injury_Leg);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Injury_Arm);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Injury_Bleeding);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Injury_Poisoned);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Injury_Grabbed);

	// Player movement and action states
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Sprinting);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Crouching);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Aiming);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Reloading);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Healing);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Hidden);
	VEILFALL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_InCutscene);
}
